[package]
name = "roids"
version = "0.1.0"
authors = ["Vickenty Fesunov <kent@setattr.net>"]

[dependencies]
cgmath = "0.6"
glutin = "0.4"
gfx = "0.9"
gfx_window_glutin = "0.9"
gfx_device_gl = "0.8"
time = "0.1"
